name: CI - Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔵 CI running with pull_request"
      - run: "Branch: ${{ github.ref }}"
      - run: "Event: ${{ github.event_name }}"
