name: AWS OIDC Lab

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write
  attestations: write

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Request OIDC Token
        run: |
          echo "Requesting token..."

          RESPONSE=$(curl -s \
                -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          echo "$RESPONSE"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug GitHub Context
        run: |
            echo "Repository : ${{ github.repository }}"
            echo "Ref        : ${{ github.ref }}"
            echo "Ref Name   : ${{ github.ref_name }}"
            echo "Run ID     : ${{ github.run_id }}"
      - name: Show Context
        run: |
            echo "Repository: ${{ github.repository }}"
            echo "Ref: ${{ github.ref }}"
            echo "Actor: ${{ github.actor }}"

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR

        id: login-ecr

        uses: aws-actions/amazon-ecr-login@v2

      - name: Verify Identity

        run: |
          aws sts get-caller-identity

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      - name: Build and Push Image

        id: build

        uses: docker/build-push-action@v6

        with:

          context: .

          file: Dockerfile

          push: true

          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

          provenance: false
  

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Container Image

        env:
          COSIGN_EXPERIMENTAL: "true"

        run: |

          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}@${{ steps.build.outputs.digest }}"

          echo "Signing ${IMAGE_URI}"

          cosign sign \
            --yes \
            "${IMAGE_URI}"
      - name: Show Digest

        run: |

          echo "Digest"

          echo "${{ steps.build.outputs.digest }}"

      - name: Generate Provenance

        uses: actions/attest-build-provenance@v2

        with:

          subject-name: |
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}

          subject-digest: |
            ${{ steps.build.outputs.digest }}

          push-to-registry: true

      
                        

      - name: Scan Base Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: |
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}@${{ steps.build.outputs.digest }}
          format: sarif
          output: trivy-image-results.sarif
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-base-image-results.sarif
      - name: Upload SARIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: trivy-base-image-results.sarif