name: Deploy Preview
on:
  pull_request_target:
    types: [ opened ]
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🟢 Preview running with pull_request_target"
      - run: "Branch: ${{ github.ref }}"
      - run: "Event: ${{ github.event_name }}"
